const modalStyles = {
    overlay: {
      position: 'fixed' as 'fixed',
      top: 0,
      left: 0,
      width: '100%',
      height: '100%',
      backgroundColor: 'rgba(0, 0, 0, 0.8)',
      display: 'flex',
      justifyContent: 'center',
      alignItems: 'center',
      zIndex: 1000,
      overflow: 'hidden' as 'hidden',
    },
    modal: {
      position: 'relative' as 'relative',
      borderRadius: '10px',
      padding: '20px',
      maxWidth: '90%',
      maxHeight: '90%',
      overflow: 'auto' as 'auto',
      display: 'flex',
      flexDirection: 'row' as 'row',
      backgroundColor: 'white',
      color:'black',
    },
    closeButton: {
      position: 'absolute' as 'absolute',
      top: '20px',
      right: '20px',
      fontSize: '20px',
      fontWeight: 'bold' as 'bold',
      cursor: 'pointer',
      backgroundColor: 'rgba(0, 0, 0, 0.7)',
      color: 'white',
      borderRadius: '10px',
      width: '40px',
      height: '40px',
      display: 'flex',
      justifyContent: 'center',
      alignItems: 'center',
    },
    image: {
      width: '100%',
      height: '100%',
      borderRadius: '10px',
    },
    detailsContainer: {
      flex: '1 1 40%',
      display: 'flex',
      flexDirection: 'column' as 'column',
      justifyContent: 'center',
      alignItems: 'flex-start',
    },
    profileImage: {
      borderRadius: '50%',
      marginTop: '10px',
    },
  };

export default modalStyles;