import type { Metadata } from "next";
import { Kanit } from "next/font/google";
import "./globals.css";


const kanit = Kanit({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  style: ["normal", "italic"],
});

export const metadata: Metadata = {
  title: "Pixorama",
  description: "Generated by create next app",
   icons:{
    icon:['/favicon.ico?=4']
   }
  }

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={kanit.className}>{children}</body>
    </html>
  );
}
